### ISSUE TITLE
Users Todo doesn't persist after refresh.

### ISSUE THREAD

**Issue by LynxSumit** [SharjeelDev/to-do-list#1]
https://github.com/sharjeelyunus/to-do-list/assets/114245865/d524bf54-a255-4e80-bd3d-f190a44f378a

I will resolve this issue via using Browser's Local Storage,
Please Assign this issue to me, after tagged this as hacktoberfest.

**Comment by sharjeelyunus** [comment]
sure, assigning this to you

**Comment by LynxSumit** [comment]
Why isn't there any labels?

**Comment by sharjeelyunus** [comment]
Just added `good first issue` label to this ticket, I'm not sure which label do you want, if its about HacktoberFest, please see hacktoberfest guidelines.

1. Repository should have tag `hacktoberfest`, see the repository, there is already
![todo](https://github.com/sharjeelyunus/to-do-list/assets/61178058/eece179c-5b5a-47b2-befb-9d6ab234348a)

2. The pull request should be merged or have `hacktoberfest-accepted` label. This is not a pull request, this is a issue/ticket, as soon as you open a PR for this ticket, I'll review it and see if it is acceptable and then add the necessary tag.
